function [SimResults,resultSummaryPre]= getSimout(out,InputPar)

SimResults.tout = out.tout;
SimResults.Sese_packCurrent_A_fd    = out.Electrical.Sese_packCurrent_A_fd.Data;
SimResults.Sese_packVoltage_V_fd    = out.Electrical.Sese_packVoltage_V_fd.Data;
SimResults.Sese_packPower_kW_fd      = SimResults.Sese_packCurrent_A_fd.*SimResults.Sese_packVoltage_V_fd./1000;
SimResults.Sese_packPower_kW_fd      = out.Electrical.Sese_packPower_kW_fd.Data; 


SimResults.Sese_packQGen_kW_fd      = out.Electrical.Sese_packQGen_kW_fd.Data; % heat generation
SimResults.CellCurrent_A            = out.Electrical.Sese_cellCurrent_A_fd.Data;

SimResults.Sese_minCellVoltage_V_fd        = out.Electrical.Sese_minCellVoltage_V_fd.Data;
SimResults.Sese_maxCellVoltage_V_fd        = out.Electrical.Sese_maxCellVoltage_V_fd.Data;
SimResults.Sese_AbsoluteSOCmin_fr_fd       = out.Electrical.Sese_AbsoluteSOCmin_fr_fd.Data;
SimResults.Sese_AbsoluteSOCmax_fr_fd       = out.Electrical.Sese_AbsoluteSOCmax_fr_fd.Data;

% Thermal results
SimResults.Sese_maxCellTemperature_degC_fd = out.Thermal.Sese_maxCellTemperature_degC_fd.Data;
SimResults.Sese_minCellTemperature_degC_fd = out.Thermal_cold.Sese_minCellTemperature_degC_fd.Data;

SimResults.Sese_hottestCellQreject_W_fd = out.Thermal.Sese_hottestCellQreject_W_fd.Data;
SimResults.Sese_coldestCellQreject_W_fd = out.Thermal_cold.Sese_coldestCellQreject_W_fd.Data;

SimResults.Sese_hottestCellQGen_W_fd= out.Electrical.Sese_cellQGen_W_fd.Data;
SimResults.Sese_coldestCellQGen_W_fd= out.Electrical_cold.Sese_cellQGen_W_fd.Data;

SimResults.Sese_coolantInletTemperature_degC_fd= out.Thermal.Sese_coolantInletTemperature_degC_fd.Data;
SimResults.Sese_coolantOutletTemperature_degC_fd= out.Thermal.Sese_coolantOutletTemperature_degC_fd.Data;
%% Find stop reasons

SimResults.StopReason = MissionHelper.findStopReason(out.StopSignals_CellHot);

%% Summurize the results
SimResults.packPower_rms_kW             = rms(SimResults.Sese_packPower_kW_fd);
SimResults.packCurrent_rms_A            = rms(SimResults.Sese_packCurrent_A_fd);
SimResults.CellTemp_max_degC            = max(SimResults.Sese_maxCellTemperature_degC_fd);
SimResults.CellVolt_max_V               = max(SimResults.Sese_maxCellVoltage_V_fd);
SimResults.CellVolt_min_V               = min(SimResults.Sese_minCellVoltage_V_fd);
SimResults.packHeatGen_rms_kW           = rms(SimResults.Sese_packQGen_kW_fd);
SimResults.packHeatGen_max_kW           = max(SimResults.Sese_packQGen_kW_fd);
SimResults.packHeatGen_kJ               = cumtrapz(SimResults.tout,SimResults.Sese_packQGen_kW_fd); %unit:kJ

SimResults.hottestCellHeatGen_kJ     = cumtrapz(SimResults.tout,SimResults.Sese_hottestCellQGen_W_fd)/1000; %unit:kJ
SimResults.hottestCellHeatReject_kJ     = cumtrapz(SimResults.tout,SimResults.Sese_hottestCellQreject_W_fd)/1000; %unit:kJ
SimResults.coldestCellHeatReject_kJ     = cumtrapz(SimResults.tout,SimResults.Sese_coldestCellQreject_W_fd)/1000; %unit:kJ
SimResults.hottestCellHeatReject_rms_W  = rms(SimResults.Sese_hottestCellQreject_W_fd); %unit:W
SimResults.coldestCellHeatReject_rms_W  = rms(SimResults.coldestCellHeatReject_kJ); %unit:W

SimResults.hottestCellHeatGen_avg_W  =  mean(SimResults.Sese_hottestCellQGen_W_fd); %unit:W
SimResults.hottestCellHeatReject_avg_W  = mean(SimResults.Sese_hottestCellQreject_W_fd); %unit:W
% SimResults.coldestCellHeatReject_avg_W  = mean(SimResults.coldestCellHeatReject_kJ); %unit:W

SimResults.coolantOutTemp_degC          = SimResults.Sese_coolantOutletTemperature_degC_fd(end);

% get the last lap of rms heat rejection and generation --> as it is
% reaching to thermal stabilization 
InputPar.TimeThermalStable_Start= 600; 
logicalIndexThermalStable= SimResults.tout>InputPar.TimeThermalStable_Start;

% find the index
% logicalIndexThermalStable= SimResults.tout>1900;


SimResults.hottestCellHeatReject_ThermalStable_rms_W = rms(SimResults.Sese_hottestCellQreject_W_fd(logicalIndexThermalStable)); %unit:W
SimResults.coldestCellHeatReject_ThermalStable_rms_W  = rms(SimResults.Sese_coldestCellQreject_W_fd(logicalIndexThermalStable)); %unit:W

SimResults.cellHeatGen_rms_W           = rms(SimResults.Sese_hottestCellQGen_W_fd);
SimResults.cellHeatGen_ThermalStable_rms_W = rms(SimResults.Sese_hottestCellQGen_W_fd(logicalIndexThermalStable));
% 
% mean(SimResults.Sese_hottestCellQGen_W_fd)
% mean(SimResults.Sese_hottestCellQGen_W_fd(logicalIndexThermalStable))


cutTime= SimResults.tout(logicalIndexThermalStable);
if ~isempty(cutTime)
cutTime=cutTime-cutTime(1);
cutHeatGen_W= SimResults.Sese_hottestCellQGen_W_fd(logicalIndexThermalStable);
cutHeatRej_W= SimResults.Sese_hottestCellQreject_W_fd(logicalIndexThermalStable);

SimResults.ThermalStable.HotCell_HeatGenAvg_W       = mean(cutHeatGen_W ); %unit:W
SimResults.ThermalStable.HotCell_HeatRejectAvg_W    = mean(cutHeatRej_W ); %unit:W

SimResults.ThermalStable.HotCell_HeatGen_kJ     = max(cumtrapz(cutTime,cutHeatGen_W)/1000); %unit:kJ
SimResults.ThermalStable.HotCell_HeatReject_kJ  = max(cumtrapz(cutTime,cutHeatRej_W)/1000); 
SimResults.ThermalStable.logicalIndexThermalStable= logicalIndexThermalStable;

end
if ~isempty( SimResults.StopReason)
    SimResults.UnfinishedLap= 1;
else
    SimResults.UnfinishedLap=0;
end

SimResults.HeatGen_pack_kJ= SimResults.packHeatGen_kJ(end);
SimResults.HeatReject_cell_hot_kJ= SimResults.hottestCellHeatReject_kJ(end);
SimResults.HeatReject_cell_cold_kJ= SimResults.coldestCellHeatReject_kJ(end);


if ~isempty(cutTime)
resultSummaryPre = table(InputPar.CoolTIn, ...
                        InputPar.CoolFlowRate, ...
                        SimResults.coolantOutTemp_degC ,...
                        InputPar.ThermalRes_CellCool_hotcell, ...
                        InputPar.ThermalRes_CellCool_coldcell, ...
                        SimResults.packPower_rms_kW,...
                        SimResults.packHeatGen_rms_kW, ...
                        SimResults.CellTemp_max_degC,...
                        SimResults.hottestCellHeatGen_avg_W ,...
                        SimResults.hottestCellHeatReject_avg_W,...
                        SimResults.hottestCellHeatGen_kJ(end),...
                        SimResults.HeatReject_cell_hot_kJ,...
                        SimResults.cellHeatGen_ThermalStable_rms_W,...                   
                        SimResults.hottestCellHeatReject_ThermalStable_rms_W,...
                        SimResults.ThermalStable.HotCell_HeatGen_kJ,...
                        SimResults.ThermalStable.HotCell_HeatReject_kJ,...
                        SimResults.ThermalStable.HotCell_HeatGenAvg_W ,...
                        SimResults.ThermalStable.HotCell_HeatRejectAvg_W  );


  resultSummaryPre.Properties.VariableNames= {'CoolTempInlet_degC', ...
                                                'CoolFlowRate_LperMin', ...
                                                'CoolTempOutlet_degC', ...
                                                'ThermalResistance_HotCell', ...
                                                'ThermalResistance_ColdCell', ...
                                                'PackPower_RMS_kW', ...
                                                'PackHeatGeneration_RMS_kW', ...
                                                'MaxCellTemperature_degC', ...
                                                'HotCellHeatGen_Avg_W',...   % Corrected comma issue
                                                'HotCellHeatRejection_Avg_W', ...
                                                'HotCellHeatGen_Energy_kJ', ...
                                                'HotCellHeatReject_Energy_kJ',...
                                                'ThermalStable_HotCellHeatGen_rms_W', ...
                                                'ThermalStable_HotCellHeatReject_rms_W', ...
                                                'ThermalStable_HotCell_HeatGen_kJ', ...
                                                'ThermalStable_HotCell_HeatReject_kJ',...
                                                 'ThermalStable_HotCell_HeatGenAvg_W', ...
                                                'ThermalStable_HotCell_HeatRejectAvg_W'};
else

resultSummaryPre = table(InputPar.CoolTIn, ...
                        InputPar.CoolFlowRate, ...
                        SimResults.coolantOutTemp_degC ,...
                        InputPar.ThermalRes_CellCool_hotcell, ...
                        InputPar.ThermalRes_CellCool_coldcell, ...
                        SimResults.packPower_rms_kW,...
                        SimResults.packHeatGen_rms_kW, ...
                        SimResults.CellTemp_max_degC,...
                        SimResults.hottestCellHeatGen_avg_W ,...
                        SimResults.hottestCellHeatReject_avg_W,...
                        SimResults.hottestCellHeatGen_kJ(end),...
                        SimResults.HeatReject_cell_hot_kJ);


  resultSummaryPre.Properties.VariableNames= {'CoolTempInlet_degC', ...
                                    'CoolFlowRate_LperMin', ...
                                    'CoolTempOutlet_degC', ...
                                    'ThermalResistance_HotCell', ...
                                    'ThermalResistance_ColdCell', ...
                                    'PackPower_RMS_kW', ...
                                    'PackHeatGeneration_RMS_kW', ...
                                    'MaxCellTemperature_degC', ...
                                    'HotCellHeatGen_Avg_W',...   % Corrected comma issue
                                    'HotCellHeatRejection_Avg_W', ...
                                    'HotCellHeatGen_Energy_kJ', ...
                                    'HotCellHeatReject_Energy_kJ'};
end
end